In [2]:
import pandas as pd
import numpy as np

In [3]:
file = np.load("/Users/shashankkumar/Documents/GitHub/MacroEcon/data/step1/all_nta_agents.npy", allow_pickle=True)
file_dict = file.item()
# df = pd.DataFrame.from_dict(dict(file_dict), orient='index')
len(file_dict.keys())

3

In [4]:
file_dict

{'empty_ntas': ['QN0151',
  'BK0261',
  'MN0661',
  'QN0261',
  'QN0761',
  'BK0471',
  'BK0571',
  'BK0771',
  'BX1071',
  'BX1271',
  'QN0171',
  'QN0271',
  'QN0572',
  'QN0573',
  'QN0871',
  'QN1371',
  'QN8081',
  'QN8381',
  'BK0891',
  'BK1091',
  'BK1391',
  'BK1891',
  'BK1892',
  'BK1893',
  'BK5591',
  'BK5692',
  'BK5693',
  'BX0291',
  'BX0391',
  'BX0491',
  'BX0492',
  'BX0991',
  'BX1091',
  'BX2691',
  'MN0191',
  'MN1291',
  'MN1292',
  'MN6491',
  'QN0191',
  'QN0791',
  'QN0891',
  'QN1091',
  'QN1491',
  'QN8191',
  'QN8291',
  'QN8491',
  'SI0191',
  'SI0291',
  'SI9591',
  'SI9593'],
 'mapping': {'race': ['hispanic',
   'white',
   'black',
   'native',
   'other',
   'asian'],
  'education': ['high_school',
   'college_degree',
   'graduate_degree',
   'studying'],
  'employment_insurance': ['employed_insured',
   'employed_uninsured',
   'unemployed_insured',
   'unemployed_uninsured',
   'nolabor_insured',
   'nolabor_uninsured'],
  'age_gender': ['U19_M',
  

In [5]:
file_dict['mapping']

{'race': ['hispanic', 'white', 'black', 'native', 'other', 'asian'],
 'education': ['high_school', 'college_degree', 'graduate_degree', 'studying'],
 'employment_insurance': ['employed_insured',
  'employed_uninsured',
  'unemployed_insured',
  'unemployed_uninsured',
  'nolabor_insured',
  'nolabor_uninsured'],
 'age_gender': ['U19_M',
  'U19_F',
  '20t29_M',
  '20t29_F',
  '30t39_M',
  '30t39_F',
  '40t49_M',
  '40t49_F',
  '50t64_M',
  '50t64_F',
  '65A_M',
  '65A_F']}

In [18]:
import torch

# Create a 3x3 tensor with random 0s and 1s
tensor_e = torch.randint(5, (1, 10))
tensor_g = torch.randint(2, (1, 10))

print(tensor_e, tensor_g)

tensor([[0, 4, 4, 3, 4, 0, 1, 0, 1, 0]]) tensor([[0, 1, 0, 0, 0, 1, 1, 0, 0, 0]])


In [19]:
tensor_chunk = torch.chunk(tensor_g, 2, 1)
tensor_chunk

(tensor([[0, 1, 0, 0, 0]]), tensor([[1, 1, 0, 0, 0]]))

In [20]:
tensor_3 = torch.where(tensor_e == 3, 0, 1)
tensor_3

tensor([[1, 1, 1, 0, 1, 1, 1, 1, 1, 1]])

In [24]:
t_eg = torch.logical_and(tensor_e == 4, tensor_g == 1).float()
t_eg

tensor([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]])