In [2]:
import numpy as np
import pandas as pd

## Calibration Data

In [3]:
file_path = './county_data.csv'

In [4]:
df = pd.read_csv(file_path)

In [5]:
df.head()

geo_value  time_value  cases  cases_monthly_avg  deaths  \
0      11101  2020-08-08    3.0                NaN     NaN   
1      11101  2020-08-15   10.0                NaN     NaN   
2      11101  2020-08-22   10.0                NaN     NaN   
3      11101  2020-08-29   15.0               10.0     NaN   
4      11101  2020-09-05    9.0               11.0     NaN   

   deaths_monthly_avg  cases_per_100K  deaths_per_100K  
0                 NaN             8.1              NaN  
1                 NaN            27.1              NaN  
2                 NaN            27.1              NaN  
3                 NaN            40.7              NaN  
4                 NaN            24.4              NaN

## Income and Employment Data

In [6]:
data_path = './llm_data/all_nta_agents.npy'

In [8]:
data = np.load(data_path, allow_pickle=True).item()

In [9]:
data.keys()

dict_keys(['BK0101', 'BK0102', 'BK0103', 'BK0104', 'BK0201', 'BK0202', 'BK0203', 'BK0204', 'BK0301', 'BK0302', 'BK0401', 'BK0402', 'BK0501', 'BK0502', 'BK0503', 'BK0504', 'BK0505', 'BK0601', 'BK0602', 'BK0701', 'BK0702', 'BK0703', 'BK0801', 'BK0802', 'BK0901', 'BK0902', 'BK1001', 'BK1002', 'BK1101', 'BK1102', 'BK1103', 'BK1201', 'BK1202', 'BK1203', 'BK1204', 'BK1301', 'BK1302', 'BK1303', 'BK1401', 'BK1402', 'BK1403', 'BK1501', 'BK1502', 'BK1503', 'BK1601', 'BK1602', 'BK1701', 'BK1702', 'BK1703', 'BK1704', 'BK1801', 'BK1802', 'BK1803', 'BX0101', 'BX0102', 'BX0201', 'BX0202', 'BX0301', 'BX0302', 'BX0303', 'BX0401', 'BX0402', 'BX0403', 'BX0501', 'BX0502', 'BX0503', 'BX0601', 'BX0602', 'BX0603', 'BX0701', 'BX0702', 'BX0703', 'BX0801', 'BX0802', 'BX0803', 'BX0901', 'BX0902', 'BX0903', 'BX0904', 'BX1001', 'BX1002', 'BX1003', 'BX1004', 'BX1101', 'BX1102', 'BX1103', 'BX1104', 'BX1201', 'BX1202', 'BX1203', 'MN0101', 'MN0102', 'MN0201', 'MN0202', 'MN0203', 'MN0301', 'MN0302', 'MN0303', 'MN0401',

In [10]:
data['BK0101']

{'nta_id': 'BK0101',
 'num_agents': 37518,
 'race_prob': [0.147, 0.727, 0.025, 0.0, 0.06199999999999999, 0.039],
 'age_gender_prob': [0.06,
  array([0.072]),
  0.08,
  array([0.1]),
  0.15,
  array([0.159]),
  0.07,
  array([0.082]),
  0.06,
  array([0.064]),
  0.04,
  array([0.064])],
 'education_prob': [0.18614058906652628,
  0.48399878085949405,
  0.18192901277326756,
  0.14793161730071208],
 'insurance_employ_prob': [0.749547983310153,
  0.06442976356050069,
  0.05027816411682893,
  0.016307371349095965,
  0.11001390820584145,
  0.009422809457579973]}