In [1]:
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

from soft import discrete_sample, logical_and

Need to write differentiable approximations for the following operations: logical_and, indicate, max

# Indicator

In [21]:
def compare(a, b):
    '''returns 1 if a > b and 2 if b > a'''
    def compare_soft(epsilon_t, nu_t, hardness=0.85):
        return torch.sigmoid(hardness * (epsilon_t - nu_t))

    def compare_hard(a, b):
        return (a > b).float()
    
    soft = compare_soft(a, b)
    return compare_hard(a, b) + soft - soft.detach()

def compare_hard(epsilon_t, nu_t):
    return (epsilon_t > nu_t).float()

a = torch.tensor(3.0, requires_grad=True)
b = torch.tensor(5.0, requires_grad=True)

x = compare(a, b)
x.backward()
print(a.grad, b.grad)

tensor(0.1110) tensor(-0.1110)


## Maximum

In [37]:
def soft_maximum(a, b):
    return a*compare(a, b) + b*compare(b, a)

value1 = torch.tensor([10.0], requires_grad=True)
value2 = torch.tensor([5.0], requires_grad=True)

hard_max = torch.max(value1, value2)
soft_max = soft_maximum(value1, value2)

print(hard_max, soft_max)
soft_max.backward()
print(value1.grad, value2.grad)

tensor([10.], grad_fn=<MaximumBackward0>) tensor([10.], grad_fn=<AddBackward0>)
tensor([1.0589]) tensor([-0.0589])


## logical_and, logical_or, logical_not

In [100]:
def logical_not(a, grad=True):
    def hard_not(a):
        assert a.dtype == torch.long
        return torch.logical_not(a)
    
    def soft_not(a):
        return 1 - a
    
    if not grad:
        return hard_not(a.long())

    soft = soft_not(a)
    return hard_not(a.long()) + soft - soft.detach()


def logical_or(a, b, grad=True):
    def hard_or(a, b):
        assert a.dtype == torch.long and b.dtype == torch.long
        return torch.logical_or(a, b)
    
    def soft_or(a, b):
        return a + b
    
    if not grad:
        return hard_or(a.long(), b.long())

    soft = soft_or(a, b)
    return hard_or(a.long(), b.long()) + (soft - soft.detach())

def logical_and(a, b, grad=True):
    def hard_and(a, b):
        assert a.dtype == torch.long and b.dtype == torch.long
        return torch.logical_and(a, b)
    
    def soft_and(a, b):
        return a * b
    
    if not grad:
        return hard_and(a.long(), b.long())

    soft = soft_and(a, b)
    return hard_and(a.long(), b.long()) + (soft - soft.detach())

## logical_or

In [101]:
x_a = torch.tensor([1.0, 0.0, 0.0, 1.0, 0.0], requires_grad=True)
x_b = torch.tensor([1.0, 0.0, 1.0, 0.0, 0.0], requires_grad=True)

z = x_a + x_b
z = logical_or(x_a, x_b)
z.sum().backward()

z2 = torch.logical_or(x_a, x_b).long()

print("Output: ", z, z2)
print("Gradient: ", x_a.grad, x_b.grad)

Output:  tensor([1., 0., 1., 1., 0.], grad_fn=<AddBackward0>) tensor([1, 0, 1, 1, 0])
Gradient:  tensor([1., 1., 1., 1., 1.]) tensor([1., 1., 1., 1., 1.])


## logical_and

In [102]:
x_a = torch.tensor([1.0, 0.0, 0.0, 1.0, 0.0], requires_grad=True)
x_b = torch.tensor([1.0, 0.0, 1.0, 0.0, 0.0], requires_grad=True)

z_basic = x_a * x_b
z_at = logical_and(x_a, x_b)
z_torch = torch.logical_and(x_a, x_b).long()
print("Output: ", z_at, z_torch)

z_at.sum().backward()
print("Gradient: ", x_a.grad, x_b.grad)

Output:  tensor([1., 0., 0., 0., 0.], grad_fn=<AddBackward0>) tensor([1, 0, 0, 0, 0])
Gradient:  tensor([1., 0., 1., 0., 0.]) tensor([1., 0., 0., 1., 0.])


## logical_not

In [105]:
x_a = torch.tensor([1.0, 0.0, 0.0, 1.0, 0.0], requires_grad=True)

z_at = logical_not(x_a)
z_torch = torch.logical_not(x_a).long()

print("Output: ", z_at, z_torch)
z_at.sum().backward()
print("Gradient: ", x_a.grad)

Output:  tensor([0., 1., 1., 0., 1.], grad_fn=<SubBackward0>) tensor([0, 1, 1, 0, 1])
Gradient:  tensor([-1., -1., -1., -1., -1.])


## discrete_sampling

In [12]:
initial_infections_percentage = torch.tensor(0.6, requires_grad=True)

agents_stages = discrete_sample(initial_infections_percentage, size=(10, 1))
print(agents_stages)
agents_stages.sum().backward()
print(initial_infections_percentage.grad)

tensor([1., 1., 0., 1., 1., 1., 0., 0., 1., 0.], grad_fn=<SelectBackward0>)
tensor(4.7663)


In [2]:
# composite operations
initial_infections_percentage = torch.tensor(0.6, requires_grad=True)
agents_stages = discrete_sample(initial_infections_percentage, size=(10, 1))

mask = torch.tensor([1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0])

out = logical_and(agents_stages, mask)
print(out)
out.sum().backward()
print(initial_infections_percentage.grad)

tensor([1., 0., 0., 0., 0., 1., 0., 1., 0., 0.], grad_fn=<AddBackward0>)
tensor(6.8792)
